services:
  app:
    image: tugboatqa/node:14
    default: true
    depends: database
    commands:
      init:
        - mkdir -p /etc/service/node
        - echo "#!/bin/sh" > /etc/service/node/run
        - echo "cd ${TUGBOAT_ROOT}" >> /etc/service/node/run
        - echo "PORT=80 DB_HOST=database DB_NAME=tugboat DB_USER=tugboat DB_PASSWORD=tugboat node ./server.js" >> /etc/service/node/run
        - chmod +x /etc/service/node/run
      build:
        - npm install
  database:
    image: tugboatqa/postgres:13
