env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

name: Docker Build & Push

on:
  push:
    branches: master

run-name: ${{ github.actor }} is testing out Docker Build & Push🚀


jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out repository code
        uses: actions/checkout@v3
      - 
        name: Log into registry ${{ env.REGISTRY }} # sign in to Github registry.
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Set up QEMU # installs QEMU static binaries for multi-arch builds
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx # initiates a BuildKit builder
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: node-postgres-sample:latest
      - 
        name: Build and Push Latest Docker Image
        id: build-and-push-latest
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          context: ./src
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}