env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

name: Docker Build & Push

on:
  push:
    branches: master

run-name: ${{ github.actor }} is testing out Docker Build & Push🚀


jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out repository code
        uses: actions/checkout@v3
      # - 
      #   name: Log into registry ${{ env.REGISTRY }} # sign in to Github registry.
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Login to GitHub Container Registry
        run: | 
          echo $GHRC_PAT | docker login ghcr.io -u ${{ github.actor }} — password-stdin
      - name: Build & Push Image
        run: |
          docker build . - tag ghcr.io/ebnerlena/node-postgres-sample:latest
          docker push ghcr.io/ebnerlena/node-postgres-sample:latest
      # - 
      #   name: Set up QEMU # installs QEMU static binaries for multi-arch builds
      #   uses: docker/setup-qemu-action@v2
      # - 
      #   name: Set up Docker Buildx # initiates a BuildKit builder
      #   uses: docker/setup-buildx-action@v2
      #   with:
      #     buildkitd-flags: --debug
      # - 
      #   name: Build and Push Docker Image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./
      #     push: true
      #     tags: | 
      #       ghcr.io/ebnerlena/node-postgres-sample:0.0.1
